apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sts
spec:
  selector:
    matchLabels:
      app: backup-restore
  serviceName: postgres-sts
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: backup-restore
    spec:
      containers:
        - name: backup-restore
          image: postgres
          ports:
            - containerPort: 5432
              name: web
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
        storageClassName: csi-hostpath-sc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: backup-restore
  ports:
    - port: 80
      targetPort: 5432
  clusterIP: None
