---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backuper
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backuper
subjects:
  - kind: ServiceAccount
    name: backuper
    namespace: default
roleRef:
  kind: ClusterRole
  name: backuper
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backuper
---

